from typing import Literal

tile_codes = [
    'AAB', 'AAC', 'AAD', 'AAE', 'AAF', 'AAG',
    'ABA', 'ABB', 'ABC', 'ABD', 'ABE', 'ABF',
    'ACA', 'ACB', 'ACC', 'ACD', 'ACE',
    'ADA', 'ADB', 'ADC', 'ADD',
    'AEA', 'AEB', 'AEC',
    'AFA', 'AFB',
    'AGA',
    'BAB', 'BAC', 'BAD', 'BAE', 'BAF', 'BAG',
    'BBA', 'BBB', 'BBC', 'BBD', 'BBE', 'BBF',
    'BCA', 'BCB', 'BCC', 'BCD', 'BCE',
    'BDA', 'BDB', 'BDC', 'BDD',
    'BEA', 'BEB', 'BEC',
    'BFA', 'BFB',
    'BGA',
    'CAB', 'CAC', 'CAD', 'CAE', 'CAF', 'CAG',
    'CBA', 'CBB', 'CBC', 'CBD', 'CBE', 'CBF',
    'CCA', 'CCB', 'CCC', 'CCD', 'CCE',
    'CDA', 'CDB', 'CDC', 'CDD',
    'CEA', 'CEB', 'CEC',
    'CFA', 'CFB',
    'CGA',
    'DAB', 'DAC', 'DAD', 'DAE', 'DAF', 'DAG',
    'DBA', 'DBB', 'DBC', 'DBD', 'DBE', 'DBF',
    'DCA', 'DCB', 'DCC', 'DCD', 'DCE',
    'DDA', 'DDB', 'DDC', 'DDD',
    'DEA', 'DEB', 'DEC',
    'DFA', 'DFB',
    'DGA',
    'EAB', 'EAC', 'EAD', 'EAE', 'EAF', 'EAG',
    'EBA', 'EBB', 'EBC', 'EBD', 'EBE', 'EBF',
    'ECA', 'ECB', 'ECC', 'ECD', 'ECE',
    'EDA', 'EDB', 'EDC', 'EDD',
    'EEA', 'EEB', 'EEC',
    'EFA', 'EFB',
    'EGA',
    'FAB', 'FAC', 'FAD', 'FAE', 'FAF', 'FAH',
    'FBA', 'FBB', 'FBC', 'FBD', 'FBE', 'FBF',
    'FCA', 'FCB', 'FCC', 'FCD', 'FCE',
    'FDA', 'FDB', 'FDC', 'FDD',
    'FEA', 'FEB', 'FEC',
    'FFA', 'FFB',
    'FGA',
    'MRX'
    ]

towers = Literal[
    "Ace",
    "Heli",
    "Dartling",
    "Super",
    "Quincy",
    "Gwendolin",
    "Striker Jones",
    "Obyn",
    "Ezili",
    "Captain Churchill",
    "Pat Fusty",
    "Admiral Brickell",
    "Adora",
    "Rosalia",
    "Geraldo"
]